Feature/activity deletion
urfit-tech/lodestar-app-admin pull request #126
Opened 2022-01-21 02:37 UTC by Ponchimeow

2022-01-21 02:38 UTC, Ponchimeow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3)【活動】活動、場次、票券要可以刪除(封存) [1]](https://trello.com/c/pVaucuT5/2678-3%E3%80%90%E6%B4%BB%E5%8B%95%E3%80%91%E6%B4%BB%E5%8B%95%E3%80%81%E5%A0%B4%E6%AC%A1%E3%80%81%E7%A5%A8%E5%88%B8%E8%A6%81%E5%8F%AF%E4%BB%A5%E5%88%AA%E9%99%A4%E5%B0%81%E5%AD%98-1)

2022-01-21 07:38 UTC, emily40830 requested changes

2022-01-21 07:38 UTC, emily40830 commented on src/hooks/activity.ts
>    return {
May have to remove this~

2022-01-21 07:38 UTC, emily40830 commented on src/components/common/MetaProductDeletionBlock.tsx
> +
NITS:You could think about how to arrange this hook when all of MetaProduct use this hook.
May like `getSimpleProduct` or other parts related to  `all products have the same action or logic` .

2022-01-24 07:41 UTC, emily40830 approved these changes

2022-01-24 07:41 UTC, merged