Feature/split program program package query
urfit-tech/lodestar-app-admin pull request #129
Opened 2022-01-24 08:19 UTC by Ponchimeow

2022-01-24 08:22 UTC, Ponchimeow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2)【課程組合、課程】load不出來 [0]](https://trello.com/c/sfuHVWd9/3010-2%E3%80%90%E8%AA%B2%E7%A8%8B%E7%B5%84%E5%90%88%E3%80%81%E8%AA%B2%E7%A8%8B%E3%80%91load%E4%B8%8D%E5%87%BA%E4%BE%86-0)

2022-01-24 11:38 UTC, emily40830 approved these changes

2022-01-24 11:38 UTC, emily40830 commented on src/hooks/programPackage.ts
>            id
`useGetProgramPackageCollection` is not a suitable naming for data hook.
You can deprecate it.
is it possible to combine `useProgramPackageCollection`data hook ?

2022-01-25 07:35 UTC, emily40830 requested changes

2022-01-25 07:35 UTC, emily40830 commented on src/hooks/programPackage.ts
> +        }
NITS

```
programPackages.forEach((programPackage)=>{
  const targetEnrollments = enrollmentData.program_package.filter(v=>v.id === programPackage.id)
  // do something for updating each programPackage enrollment from targetEnrollments
  // ....
})

```

2022-01-25 07:35 UTC, emily40830 commented on src/hooks/programPackage.ts
>      gql`
NOTE: same issue
useGetProgramPackage => useProgramPackage

2022-01-25 07:35 UTC, emily40830 commented on src/pages/ProgramCollectionAdminPage.tsx
> +        }
same issue

2022-01-26 12:45 UTC, emily40830 approved these changes

2022-01-26 12:45 UTC, merged