[FEATURE] add project_auto_delivery module
urfit-tech/lodestar-app-admin pull request #138
Opened 2022-02-18 09:16 UTC by Ponchimeow

2022-02-18 09:25 UTC, Ponchimeow commented
![](https://github.trello.services/images/mini-trello-icon.png) [【專案】希望先切成「專案自動交付」之類的模組](https://trello.com/c/xxyf4iVM/3141-%E3%80%90%E5%B0%88%E6%A1%88%E3%80%91%E5%B8%8C%E6%9C%9B%E5%85%88%E5%88%87%E6%88%90%E3%80%8C%E5%B0%88%E6%A1%88%E8%87%AA%E5%8B%95%E4%BA%A4%E4%BB%98%E3%80%8D%E4%B9%8B%E9%A1%9E%E7%9A%84%E6%A8%A1%E7%B5%84)

2022-02-21 06:16 UTC, emily40830 requested changes

2022-02-21 06:16 UTC, emily40830 commented on src/components/project/ProjectPlanAdminModal.tsx
> +          <Form.Item name="planProducts" label={formatMessage(projectMessages.ProjectPlanAdminModal.deliverables)}>
just use 
```
  {enabledModules.project_auto_delivery && ( ...

```
not work ?

2022-02-21 15:11 UTC, emily40830 approved these changes

2022-02-21 15:11 UTC, merged