[FEATURE] member notes add searching block
urfit-tech/lodestar-app-admin pull request #170
Opened 2022-06-09 03:08 UTC by clothe09986

2022-06-09 03:08 UTC, clothe09986 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) 【聯絡記錄】希望放搜尋關鍵字的框，外層也要一起 [1]](https://trello.com/c/TppIzM4a/3393-1-%E3%80%90%E8%81%AF%E7%B5%A1%E8%A8%98%E9%8C%84%E3%80%91%E5%B8%8C%E6%9C%9B%E6%94%BE%E6%90%9C%E5%B0%8B%E9%97%9C%E9%8D%B5%E5%AD%97%E7%9A%84%E6%A1%86%EF%BC%8C%E5%A4%96%E5%B1%A4%E4%B9%9F%E8%A6%81%E4%B8%80%E8%B5%B7-1)

2022-06-10 03:30 UTC, sunnylochun requested changes

2022-06-10 03:30 UTC, sunnylochun commented on src/hooks/member.ts
> +    description: { _like: `%${keyword}%` },
FIX: if there no keyword, don't need description condition
because empty like condition can not fetch null description

2022-06-15 03:34 UTC, Ponchimeow approved these changes

2022-06-15 07:00 UTC, merged