update csv setting
urfit-tech/lodestar-app-admin pull request #281
Opened 2023-03-10 17:37 UTC by brain00021

1. change CSV setting

2023-03-10 17:38 UTC, brain00021 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) 【學習進度】學習進度表上測驗顯示通過也有測驗通過時間，但總課程完成率為0%](https://trello.com/c/yyLfjwGb/17-1-%E3%80%90%E5%AD%B8%E7%BF%92%E9%80%B2%E5%BA%A6%E3%80%91%E5%AD%B8%E7%BF%92%E9%80%B2%E5%BA%A6%E8%A1%A8%E4%B8%8A%E6%B8%AC%E9%A9%97%E9%A1%AF%E7%A4%BA%E9%80%9A%E9%81%8E%E4%B9%9F%E6%9C%89%E6%B8%AC%E9%A9%97%E9%80%9A%E9%81%8E%E6%99%82%E9%96%93%EF%BC%8C%E4%BD%86%E7%B8%BD%E8%AA%B2%E7%A8%8B%E5%AE%8C%E6%88%90%E7%8E%87%E7%82%BA0)

2023-03-15 14:59 UTC, Ponchimeow commented on src/pages/ProgramProgressCollectionAdminPage/ProgramProcessBlock.tsx
> +                  hightestScore.totalGainedPoints > 0
if ths score pass the exam is 100%
unanswer or not pass is 0
check the conditional operator

2023-03-15 15:07 UTC, Ponchimeow requested changes

2023-03-15 15:07 UTC, Ponchimeow commented on src/pages/ProgramProgressCollectionAdminPage/ProgramProcessBlock.tsx
> +                    : ((memberWatchedDuration / (programDuration || 1)) * 100).toFixed(0) + '%',
this column is totalPercentage
should be caculate by each program content body's type
if the body type is exam or exercise, decide by passing or not

2023-03-27 06:29 UTC, Ponchimeow approved these changes

2023-03-27 13:21 UTC, merged