fix: modify GET_PRACTICE_PREVIEW_COLLECTION condition
urfit-tech/lodestar-app-admin pull request #330
Opened 2023-07-04 06:33 UTC by HLTVProxy

- modify GET_PRACTICE_PREVIEW_COLLECTION condition for practice search

requirement:
https://www.kimibarre.net/admin/practices
這個頁面中，無法以使用者名稱搜尋繳交的作業。

經查發現：送出的 variable 應該要是

```
{
  "condition": {
    "_or": [
      {
        "member": {
          "name": {
            "_like": "%洪璟旎%"
          }
        }
      },
      {
        "title": {
          "_like": "%洪璟旎%"
        }
      }
    ],
......
  "limit": 20
}
```

原本送出的是

```
{
  "condition": {
    "_or": [
      {
        "member": {
          "username": {
            "_like": "%洪璟旎%"
          }
        }
      },
      {
        "title": {
          "_like": "%洪璟旎%"
        }
      }
    ],
......
  "limit": 20
}
```

據改即可。

2023-07-04 06:34 UTC, HLTVProxy commented
![](https://github.trello.services/images/mini-trello-icon.png) [【作業管理】無法以使用者名稱搜尋作業](https://trello.com/c/Foz0uX71/2052-%E3%80%90%E4%BD%9C%E6%A5%AD%E7%AE%A1%E7%90%86%E3%80%91%E7%84%A1%E6%B3%95%E4%BB%A5%E4%BD%BF%E7%94%A8%E8%80%85%E5%90%8D%E7%A8%B1%E6%90%9C%E5%B0%8B%E4%BD%9C%E6%A5%AD)

2023-07-05 17:13 UTC, clothe09986 requested changes

2023-07-06 08:24 UTC, HLTVProxy commented on src/pages/PracticeCollectionAdminPage.tsx
>        { member: { username: { _like: options?.searchText ? `%${options.searchText}%` : undefined } } },
為了保證舊有如果使用 username 可以搜尋的
避免修A壞B

2023-07-06 08:39 UTC, clothe09986 commented on src/pages/PracticeCollectionAdminPage.tsx
>        { member: { username: { _like: options?.searchText ? `%${options.searchText}%` : undefined } } },
I don't have any issues about the code, so I approve it first.
But I suggest to discuss about the use case with ZZ.

2023-07-06 08:39 UTC, clothe09986 approved these changes

2023-07-06 08:39 UTC, merged

2023-07-06 08:42 UTC, HLTVProxy commented on src/pages/PracticeCollectionAdminPage.tsx
>        { member: { username: { _like: options?.searchText ? `%${options.searchText}%` : undefined } } },
我有跟 Logos 還有 ZZ 確認過了