feat: add not individually sale checkbox in PodcastProgramPlanForm
urfit-tech/lodestar-app-admin pull request #337
Opened 2023-07-13 10:32 UTC by HLTVProxy

- add not individually sale checkbox in PodcastProgramPlanForm

requirement:
在銷售方案的頁面上，希望可以勾選「無單集銷售」；勾選後，底下「定價」與「優惠價」區域可以直接 display: none; 。
https://samplepage.kolable.app/admin/podcast-programs/7fe131c1-6db6-4e61-acc6-c9313d88c24d?tab=plan

2023-07-13 10:41 UTC, HLTVProxy commented
![](https://github.trello.services/images/mini-trello-icon.png) [【音頻】銷售方案可選擇無單集銷售](https://trello.com/c/cErmCRxI/2120-%E3%80%90%E9%9F%B3%E9%A0%BB%E3%80%91%E9%8A%B7%E5%94%AE%E6%96%B9%E6%A1%88%E5%8F%AF%E9%81%B8%E6%93%87%E7%84%A1%E5%96%AE%E9%9B%86%E9%8A%B7%E5%94%AE)

2023-07-17 03:59 UTC, Ponchimeow commented on src/components/podcast/PodcastProgramPlanForm.tsx
> +  }, [podcastProgramAdmin])
useEffect is not necessary
default state can be `!!podcastProgramAdmin.isIndividuallySale`

2023-07-17 04:09 UTC, Ponchimeow requested changes

2023-07-17 04:09 UTC, Ponchimeow commented on src/components/podcast/PodcastProgramPlanForm.tsx
>          soldAt: values.sale?.soldAt || null,
when isIndividuallySale is false
listPrice, salePrice, soldAt can be system default value ( 0 or null

2023-07-17 04:26 UTC, HLTVProxy commented on src/components/podcast/PodcastProgramPlanForm.tsx
> +  }, [podcastProgramAdmin])
這是需要的
因為 podcastProgramAdmin 一進來是 undefined
所以 isIndividuallySale 的預設狀態會是錯的
需要用 useEffet 確認 podcastProgramAdmin 有東西
再做正確的初始化

2023-07-17 04:29 UTC, HLTVProxy commented on src/components/podcast/PodcastProgramPlanForm.tsx
>          soldAt: values.sale?.soldAt || null,
已調整

2023-07-17 06:11 UTC, Ponchimeow commented on src/components/podcast/PodcastProgramPlanForm.tsx
> +  }, [podcastProgramAdmin])
+ change usePodcastProgramAdmin hooks in podcast.ts
  + remove line 160 to 162, use `data.

+ add loading Skeleton in PodcastProgramAdminPage

2023-07-18 08:26 UTC, Ponchimeow approved these changes

2023-07-18 08:27 UTC, merged