feat: setting craft page with footer and header
urfit-tech/lodestar-app-admin pull request #354
Opened 2023-08-14 20:06 UTC by aniku777tw

2023-08-14 20:07 UTC, aniku777tw commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3)【頁面管理】自訂版型優化，新增空白版型＋可支援js與jquery+會員資料SDK](https://trello.com/c/xkrpAxsm/4548-3%E3%80%90%E9%A0%81%E9%9D%A2%E7%AE%A1%E7%90%86%E3%80%91%E8%87%AA%E8%A8%82%E7%89%88%E5%9E%8B%E5%84%AA%E5%8C%96%EF%BC%8C%E6%96%B0%E5%A2%9E%E7%A9%BA%E7%99%BD%E7%89%88%E5%9E%8B%EF%BC%8B%E5%8F%AF%E6%94%AF%E6%8F%B4js%E8%88%87jquery%E6%9C%83%E5%93%A1%E8%B3%87%E6%96%99sdk)

2023-08-14 20:07 UTC, aniku777tw commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3)【頁面管理】自訂版型優化，新增空白版型＋可支援js與jquery+會員資料SDK](https://trello.com/c/xkrpAxsm/4548-3%E3%80%90%E9%A0%81%E9%9D%A2%E7%AE%A1%E7%90%86%E3%80%91%E8%87%AA%E8%A8%82%E7%89%88%E5%9E%8B%E5%84%AA%E5%8C%96%EF%BC%8C%E6%96%B0%E5%A2%9E%E7%A9%BA%E7%99%BD%E7%89%88%E5%9E%8B%EF%BC%8B%E5%8F%AF%E6%94%AF%E6%8F%B4js%E8%88%87jquery%E6%9C%83%E5%93%A1%E8%B3%87%E6%96%99sdk)

2023-08-16 03:20 UTC, clothe09986 requested changes

2023-08-16 03:20 UTC, clothe09986 commented on src/pages/CraftPageCollectionPage/CraftPageCreationModal.tsx
> +  const [pageId, setPageId] = useState<string>()
I think this state is unnecessary. We can get the `pageId` after `insertAppPage` and then route to it.

2023-08-16 03:20 UTC, clothe09986 commented on src/pages/CraftPageCollectionPage/CraftPageCreationModal.tsx
> +    }
here

2023-08-16 03:20 UTC, clothe09986 commented on src/pages/CraftPageCollectionPage/CraftPageCreationModal.tsx
> +      }}
Then we don't need this part.

2023-08-16 03:21 UTC, clothe09986 commented on src/pages/CraftPageCollectionPage/CraftPageCreationModal.tsx
> +  const [pageId, setPageId] = useState<string>()
https://github.com/urfit-tech/lodestar-app-admin/pull/354#discussion_r1295337209

2023-08-16 03:49 UTC, aniku777tw commented on src/pages/CraftPageCollectionPage/CraftPageCreationModal.tsx
> +      }}
modified

2023-08-16 03:49 UTC, aniku777tw commented on src/pages/CraftPageCollectionPage/CraftPageReplicateModal.tsx
> +  console.log(originCraftPage)
modified

2023-08-16 03:51 UTC, aniku777tw commented
updated

2023-08-16 05:29 UTC, clothe09986 approved these changes

2023-08-16 05:29 UTC, merged