fix: modify AppNavAdminCard
urfit-tech/lodestar-app-admin pull request #359
Opened 2023-08-24 03:48 UTC by HLTVProxy

requirement:

頁面網址:https://www.acrossbeavers.com/admin/app/basic
登入帳號：zihrou@qraft.app / 12345678
描述：由於後台編輯 header 與 footer 的連結區域是必填欄位，導致他們如果要編輯 header 或 footer 時按下儲存會被前端擋掉而無法編輯(如圖)

因此需調整後台選單設定

將元件改為可設定子選單＋調整排序

設計稿
https://zpl.io/JEljWQE
https://zpl.io/z80v7wX

2023-08-24 03:51 UTC, HLTVProxy commented
![](https://github.trello.services/images/mini-trello-icon.png) [【選單】目前的版型無法設定子選單footer+新增選單操作體驗優化](https://trello.com/c/UsDW0WU1/2367-%E3%80%90%E9%81%B8%E5%96%AE%E3%80%91%E7%9B%AE%E5%89%8D%E7%9A%84%E7%89%88%E5%9E%8B%E7%84%A1%E6%B3%95%E8%A8%AD%E5%AE%9A%E5%AD%90%E9%81%B8%E5%96%AEfooter%E6%96%B0%E5%A2%9E%E9%81%B8%E5%96%AE%E6%93%8D%E4%BD%9C%E9%AB%94%E9%A9%97%E5%84%AA%E5%8C%96)

2023-08-29 18:14 UTC, clothe09986 requested changes

2023-08-29 18:14 UTC, clothe09986 commented on src/pages/AppBasicAdminPage/AppNavAdminCard.tsx
I noticed that AppNavAdminCard use `AppHeaderNavModal` four times for `add nav`, `edit nav`, `add sub nav` and `edit sub nav`,and the way to distinguish them is through the changes of props. I think it's not reader-friendly.
Perhaps, we can manage the control externally in AppNavAdminCard, not in AppHeaderNavModal. So we can add four distinct buttons to control modal visibility, and just use one AppHeaderNavModal with different props.

2023-08-30 05:23 UTC, HLTVProxy commented on src/pages/AppBasicAdminPage/AppHeaderNavModal.tsx
> +            </Form.Item>
因為他不能個別設置，只能全域設置
跟 ZZ 討論過了，說拔掉沒關係

2023-08-30 05:30 UTC, HLTVProxy commented on src/pages/AppBasicAdminPage/AppNavAdminCard.tsx
> +type ItemProps = AppNavProps
方便辨認

2023-08-30 05:31 UTC, HLTVProxy commented on src/pages/AppBasicAdminPage/AppHeaderNavModal.tsx
> +              >
OK 我拔掉

2023-08-30 05:35 UTC, HLTVProxy commented on src/pages/AppBasicAdminPage/AppHeaderNavModal.tsx
> +          <Form.Item className="col-6" name="locale" label={<StyledFormLabel>顯示語系</StyledFormLabel>}>
已修正

2023-08-30 05:52 UTC, HLTVProxy commented on src/pages/AppBasicAdminPage/AppHeaderNavModal.tsx
> +        </Form.Item>
已修正

2023-08-30 06:15 UTC, HLTVProxy commented on src/pages/AppBasicAdminPage/AppNavAdminCard.tsx
已修正

2023-08-30 18:36 UTC, clothe09986 requested changes

2023-08-30 18:36 UTC, clothe09986 commented on src/pages/AppBasicAdminPage/translation.ts
> +    },
`選單連結` ？

2023-08-30 18:36 UTC, clothe09986 commented on src/pages/AppBasicAdminPage/AppNavAdminCard.tsx
> +            access?.scrollIntoView(true)
Why does it scroll to the first position after updating?

2023-08-30 18:36 UTC, clothe09986 commented on src/pages/AppBasicAdminPage/AppNavAdminCard.tsx
But I still see four modals. I suggest using four buttons to trigger a single modal. It would be more intuitive.

2023-08-31 06:41 UTC, HLTVProxy commented on src/pages/AppBasicAdminPage/AppNavAdminCard.tsx
> +            access?.scrollIntoView(true)
因為他 refetch 之後會跳到頁面最上面
所以需要做這個動作

2023-08-31 06:42 UTC, HLTVProxy commented on src/pages/AppBasicAdminPage/translation.ts
> +    },
已修改

2023-09-01 04:31 UTC, clothe09986 requested changes

2023-09-01 04:31 UTC, clothe09986 commented on src/pages/AppBasicAdminPage/AppNavAdminCard.tsx
>                            </Button>
This button is for adding a sub nav. Shouldn't we check if it's the header?

2023-09-01 05:02 UTC, HLTVProxy commented on src/pages/AppBasicAdminPage/AppNavAdminCard.tsx
>                            </Button>
重構的時候忘記補回去了
已修正

2023-09-01 11:21 UTC, clothe09986 approved these changes
NIT:
I suggest that when adding a sub nav, the link of the main nav should be removed. 
Otherwise, when a user clicks on the main nav, it will directly route to the link.

2023-09-01 11:22 UTC, merged