Fix/synchronize archived meetings
urfit-tech/lodestar-app-admin pull request #474
Opened 2024-04-22 03:43 UTC by Ponchimeow

<img width="1111" alt="image" src="https://github.com/urfit-tech/lodestar-app-admin/assets/28040359/a23ed3db-3355-4736-ae7f-dae64cf361ae">

+ 預約紀錄取消預約時, 除了在 order_product 上壓上取消時間, 也一併封存 meet

2024-04-22 03:44 UTC, Ponchimeow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1)【待辦清單】第一個待辦ZOOM原定3小時，提早結束調整為2小時，第二個待辦同一組人員想提早會議時間，會吃第一次建立會議的時長，因此無法儲存](https://trello.com/c/d9obOmsA/5266-1%E3%80%90%E5%BE%85%E8%BE%A6%E6%B8%85%E5%96%AE%E3%80%91%E7%AC%AC%E4%B8%80%E5%80%8B%E5%BE%85%E8%BE%A6zoom%E5%8E%9F%E5%AE%9A3%E5%B0%8F%E6%99%82%EF%BC%8C%E6%8F%90%E6%97%A9%E7%B5%90%E6%9D%9F%E8%AA%BF%E6%95%B4%E7%82%BA2%E5%B0%8F%E6%99%82%EF%BC%8C%E7%AC%AC%E4%BA%8C%E5%80%8B%E5%BE%85%E8%BE%A6%E5%90%8C%E4%B8%80%E7%B5%84%E4%BA%BA%E5%93%A1%E6%83%B3%E6%8F%90%E6%97%A9%E6%9C%83%E8%AD%B0%E6%99%82%E9%96%93%EF%BC%8C%E6%9C%83%E5%90%83%E7%AC%AC%E4%B8%80%E6%AC%A1%E5%BB%BA%E7%AB%8B%E6%9C%83%E8%AD%B0%E7%9A%84%E6%99%82%E9%95%B7%EF%BC%8C%E5%9B%A0%E6%AD%A4%E7%84%A1%E6%B3%95%E5%84%B2%E5%AD%98)

2024-04-23 03:52 UTC, TedxTed requested changes

2024-04-23 03:52 UTC, TedxTed commented on src/translations/locales/en-us.json
> +  "form.PermissionGroup.MEMBER_COUPON_PLAN_VIEW": "查看會員折價券資訊",
need to translate to the English version

2024-04-23 05:18 UTC, TedxTed approved these changes

2024-04-23 05:18 UTC, merged