feat:add video upload functionality
urfit-tech/lodestar-app-admin pull request #509
Opened 2024-06-07 10:59 UTC by ShenDing1125

add video upload functionality

2024-06-07 10:59 UTC, ShenDing1125 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3)【課程管理】可以切換課程簡介頁版型的功能](https://trello.com/c/RdOBtK6f/5315-3%E3%80%90%E8%AA%B2%E7%A8%8B%E7%AE%A1%E7%90%86%E3%80%91%E5%8F%AF%E4%BB%A5%E5%88%87%E6%8F%9B%E8%AA%B2%E7%A8%8B%E7%B0%A1%E4%BB%8B%E9%A0%81%E7%89%88%E5%9E%8B%E7%9A%84%E5%8A%9F%E8%83%BD)

2024-06-10 09:33 UTC, LoisChen68 commented on src/pages/ProgramAdminPage/ProgramCoverForm.tsx
> +      : validateFile(coverMobileMedia.name) === 'image'
Using `coverMedia.type`.
Please try `console.log(coverMedia)` to see data  when uploading the file.

And whether `coverMobileUrl` should upload the video format needs to be confirmed.

2024-06-10 09:33 UTC, LoisChen68 commented on src/pages/ProgramAdminPage/ProgramCoverForm.tsx
> +        mobileCoverType: coverMobileMedia ? validateFile(coverMobileMedia.name) : 'image',
Using `coverMedia.type`.
Please try `console.log(coverMedia)` to see data  when uploading the file.

2024-06-10 09:36 UTC, LoisChen68 commented on src/pages/ProgramAdminPage/ProgramCoverForm.tsx
> +            {isShowOriginSizeCover && (
If it is confirmed that this `checkbox` does not need to be displayed in the video format, you can using `coverMidea.type` without use setState.

2024-06-10 09:36 UTC, LoisChen68 commented on src/pages/ProgramAdminPage/ProgramCoverForm.tsx
> +
Use `coverMedia.type` to whether to display, don’t need this `useEffect`.

2024-06-10 09:42 UTC, LoisChen68 requested changes
Please modify code or reply to comment.

2024-06-12 09:11 UTC, merged