Feat/transcript modal
urfit-tech/lodestar-app-admin pull request #530
Opened 2024-07-01 12:28 UTC by Ponchimeow

+ transcript when click button
+ transcript status
+ translation

2024-07-01 12:29 UTC, Ponchimeow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2)【聯絡記錄】逐字稿功能希望改為手動執行後才產出逐字稿](https://trello.com/c/gUgVkLAn/5385-2%E3%80%90%E8%81%AF%E7%B5%A1%E8%A8%98%E9%8C%84%E3%80%91%E9%80%90%E5%AD%97%E7%A8%BF%E5%8A%9F%E8%83%BD%E5%B8%8C%E6%9C%9B%E6%94%B9%E7%82%BA%E6%89%8B%E5%8B%95%E5%9F%B7%E8%A1%8C%E5%BE%8C%E6%89%8D%E7%94%A2%E5%87%BA%E9%80%90%E5%AD%97%E7%A8%BF)

2024-07-04 09:33 UTC, TedxTed requested changes

2024-07-04 09:33 UTC, TedxTed commented on src/components/member/translation.ts
> +      defaultMessage: '確定要轉換為逐字稿嗎?',
default message need english version

2024-07-04 09:33 UTC, TedxTed commented on src/components/member/translation.ts
> +      defaultMessage: '執行後將會需要一些時間進行轉換',
default message need english version

2024-07-04 09:33 UTC, TedxTed commented on src/components/member/translation.ts
> +      defaultMessage: '逐字稿轉換失敗',
default message need english version

2024-07-04 09:33 UTC, TedxTed commented on src/components/member/translation.ts
> +      defaultMessage: '備註一經刪除即不可恢復，確定要刪除嗎？',
default message need english version

2024-07-05 06:35 UTC, merged