Feat/ebook other settings
urfit-tech/lodestar-app-admin pull request #538
Opened 2024-07-17 09:51 UTC by Ponchimeow

2024-07-18 02:42 UTC, Ponchimeow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2)【課程管理】後台-新增欄位](https://trello.com/c/YGuJNhrU/5394-2%E3%80%90%E8%AA%B2%E7%A8%8B%E7%AE%A1%E7%90%86%E3%80%91%E5%BE%8C%E5%8F%B0-%E6%96%B0%E5%A2%9E%E6%AC%84%E4%BD%8D)

2024-07-23 01:24 UTC, clothe09986 requested changes

2024-07-23 01:24 UTC, clothe09986 commented on src/types/program.ts
> +    options?: any
I think we can define the `options` type with typescript generics
ex:
```
interface TextEditorOptionType {
  controls: ControlType[];
}

interface BaseField<T extends string, O = any> {
  id: string;
  name: string;
  type: T;
  options?: O;
}

type TextField = BaseField<"Text">;

type TextEditorField = BaseField<"TextEditor", TextEditorOptionType>;

type Field = TextField | TextEditorField;
```

2024-07-23 04:38 UTC, clothe09986 approved these changes

2024-07-23 05:02 UTC, merged