Feat/add announcement path exact and contains mathing
urfit-tech/lodestar-app-admin pull request #539
Opened 2024-07-18 09:43 UTC by TedxTed

1. add options for exact matching and partial matching when checking paths.
2. add hour and minute settings for remind period selector

2024-07-18 09:43 UTC, TedxTed commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2)【公告管理】設定指定路徑公告，其他頁面卻也出現公告＋公告希望有預覽功能＋週期調整＋權限](https://trello.com/c/Tx8D2HDL/5408-2%E3%80%90%E5%85%AC%E5%91%8A%E7%AE%A1%E7%90%86%E3%80%91%E8%A8%AD%E5%AE%9A%E6%8C%87%E5%AE%9A%E8%B7%AF%E5%BE%91%E5%85%AC%E5%91%8A%EF%BC%8C%E5%85%B6%E4%BB%96%E9%A0%81%E9%9D%A2%E5%8D%BB%E4%B9%9F%E5%87%BA%E7%8F%BE%E5%85%AC%E5%91%8A%EF%BC%8B%E5%85%AC%E5%91%8A%E5%B8%8C%E6%9C%9B%E6%9C%89%E9%A0%90%E8%A6%BD%E5%8A%9F%E8%83%BD%EF%BC%8B%E9%80%B1%E6%9C%9F%E8%AA%BF%E6%95%B4%EF%BC%8B%E6%AC%8A%E9%99%90)

2024-07-25 17:21 UTC, clothe09986 requested changes

2024-07-25 17:21 UTC, clothe09986 commented on src/types/announcement.ts
> +import { PeriodType } from "./general"
Should modify it in lodestar-app-element

2024-07-25 17:21 UTC, clothe09986 commented on src/components/announcement/AnnouncementPathSettingsForm.tsx
> +  }, [value])
Don't need useEffect for initialization.

2024-07-25 17:21 UTC, clothe09986 commented on src/components/announcement/AnnouncementPathSettingsForm.tsx
> +  const [radioValues, setRadioValues] = useState<string[]>(
The name `radioValue` seems like a single value. I think renaming it to `pathMatchTypes` would be better.

2024-07-26 03:59 UTC, clothe09986 approved these changes

2024-07-26 03:59 UTC, merged