feat: sales lead api
urfit-tech/lodestar-app-admin pull request #555
Opened 2024-08-23 09:07 UTC by Ponchimeow

2024-08-23 13:45 UTC, clothe09986 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2)【名單撥打】業務反應有時候按了拒絕，但實際上卻沒有真的拒絕，名單卻還是在他名單池內（但操作拒絕的過程都是正常的）](https://trello.com/c/WAyFAxAx/5510-2%E3%80%90%E5%90%8D%E5%96%AE%E6%92%A5%E6%89%93%E3%80%91%E6%A5%AD%E5%8B%99%E5%8F%8D%E6%87%89%E6%9C%89%E6%99%82%E5%80%99%E6%8C%89%E4%BA%86%E6%8B%92%E7%B5%95%EF%BC%8C%E4%BD%86%E5%AF%A6%E9%9A%9B%E4%B8%8A%E5%8D%BB%E6%B2%92%E6%9C%89%E7%9C%9F%E7%9A%84%E6%8B%92%E7%B5%95%EF%BC%8C%E5%90%8D%E5%96%AE%E5%8D%BB%E9%82%84%E6%98%AF%E5%9C%A8%E4%BB%96%E5%90%8D%E5%96%AE%E6%B1%A0%E5%85%A7%EF%BC%88%E4%BD%86%E6%93%8D%E4%BD%9C%E6%8B%92%E7%B5%95%E7%9A%84%E9%81%8E%E7%A8%8B%E9%83%BD%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%EF%BC%89)

2024-08-28 03:38 UTC, TedxTed requested changes

2024-08-28 03:38 UTC, TedxTed commented on src/hooks/sales.ts
> +              ...salesLeadMember,
It's good to explicitly list each field with conversion when the results come from an external api

2024-08-28 05:08 UTC, LoisChen68 approved these changes

2024-08-28 09:41 UTC, TedxTed approved these changes

2024-08-28 09:41 UTC, merged